/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

#include <string>
#include <unordered_map>
using namespace std;


#if 0
class Solution {
public:
    char findTheDifference(string s, string t) {
        unordered_map<char, int> mci;
        for(auto c : s) {
            mci[c]++;
        }
        for(auto c : t) {
            if (mci[c] == 0) {
                return c;
            }
            else {
                mci[c] --;
            }
        }
        return ' ';
    }
};
#endif

#if 1
class Solution {
public:
    char findTheDifference(string s, string t) {
        char r = 0;
        for (auto c : s) {
            r ^= c;
        }
        for (auto c : t) {
            r ^= c;
        }
        
        return r;
    }
};
#endif
